# Generated by Django 6.0.3 on 2026-04-06 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervenciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='intervencion',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='intervencion',
            name='direccion',
        ),
        migrations.AddField(
            model_name='intervencion',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intervencion',
            name='trabajo_realizado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intervencion',
            name='estado',
            field=models.CharField(choices=[('averia', 'Avería'), ('en_proceso', 'En proceso'), ('finalizada', 'Finalizada'), ('parte_entregado', 'Parte entregado')], default='averia', max_length=20),
        ),
        migrations.CreateModel(
            name='Puerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('ubicacion', models.CharField(max_length=255)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puertas', to='intervenciones.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='intervencion',
            name='puerta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intervenciones', to='intervenciones.puerta'),
        ),
    ]
